# Root directory to locate the content
# Default is the root directory of the repository.
root: ./docs/
# ​
# # Files to use as SUMMARY/README.
# # (Relative to <root> directory)
# structure:
#   readme: README.md
#   summary: README.md
# ​
# # Redirect urls to specific files (relative to the <root> directory)
# redirects:
# # previous/page: new-folder/page.md