site_name: GraphCMS Documentation
# Project information
site_description: 'A GraphQL based Headless Content Management System'
site_author: 'Michael Lukaszczyk & Daniel Winter'
site_url: 'https://graphcms.com/docs'

# Repository
repo_name: graphcms/docs
repo_url: https://github.com/graphcms/docs
edit_uri: ""

# Documentation and theme
theme:
  name: null
  language: 'en'
  custom_dir: 'theme/material'
  logo: 'img/graphcms_logo.svg'
  favicon: 'assets/images/favicon.ico'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  feature:
    tabs: false


# Options
extra:
  base_url: 'https://graphcms.com/docs'
  social:
    - type: 'github'
      link: 'https://github.com/graphcms'
    - type: 'twitter'
      link: 'https://twitter.com/graphcms'
    - type: 'facebook'
      link: 'https://facebook.com/graphcms'
    - type: 'instagram'
      link: 'https://instagram.com/graphcms'
  search:
    language: 'en'

# Copyright
copyright: 'Copyright &copy; 2018 GraphCMS'

extra_css:
  - 'stylesheets/extra.css'
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: "#"

pages:
- Introduction: 'Introduction.md'
- Concepts: 'Concepts.md'
- Getting Started: 
  - 'Setting up the Blog Example Project': 'getting-started/Setting_up_the_project.md'
  - 'Beginners Guide with React': 'getting-started/Beginners_Guide_With_React.md'
  - 'Beginners Guide with Vue': 'getting-started/Beginners_Guide_With_Vue.md'
- Assets:
  - 'General': 'assets/General.md'
  - 'Querying an Asset Field': 'assets/Querying_Assets_Field.md'
  - Transformations:
    - 'Transforming URL Structure': 'assets/Transforming_URL_Structure.md'
    - 'Resize Fit and Align' : 'assets/Resize_Fit_Align.md'
    - 'Crop' : 'assets/Crop.md'
    - 'Rotate': 'assets/Rotate.md'
    - 'Flip': 'assets/Flip.md'
    - 'Flop': 'assets/Flop.md'
    - 'Watermark': 'assets/Watermark.md'
    - Facial Detection:
      - 'Detect Faces': 'assets/facial_detection/Detect_Faces.md'
      - 'Crop Faces': 'assets/facial_detection/Crop_Faces.md'
      - 'Pixelate Faces': 'assets/facial_detection/Pixelate_Faces.md'
      - 'Blur Faces': 'assets/facial_detection/Blur_Faces.md'
    - 'Filetype Conversions': 'assets/Filetype_Conversions.md'
    - 'Compress': 'assets/Compress.md'
    - 'Change Quality': 'assets/Change_Quality.md'
  - 'Chaining Transformations': 'assets/Chanining_Transformations.md'
- Integrations:
  - 'integrations/Algolia.md'
- Examples:
  - 'Gatsby & gatsby-source-graphcms': 'examples/Gatsby_Source-plugin_Blog.md'
  - 'Next.js & Apollo Client': 'examples/Next_Apollo_Blog.md'
  - 'Nuxt.js & Apollo Client': 'examples/Nuxt_Apollo_Blog.md'
  - 'PreactCLI & Apollo Client': 'examples/Preact-CLI_Apollo_Blog.md'
  - 'React & Apollo Client': 'examples/React_Apollo_Blog.md'
  - 'React & URQL': 'examples/React_URQL_Blog.md'
  - 'React Native & Apollo Client': 'examples/React-Native_Apollo_Blog.md'
  - 'React Static & graphql-request': 'examples/React-Static_GraphQL_Request_Blog.md'
  - 'Using Spike': 'examples/Spike_Vinylbase.md'
  - 'RSS Feed - VanillaJS & apollo-fetch': 'examples/Vanillajs_Apollo-fetch_RSS_feed.md'
  - 'Vue & Apollo Client': 'examples/Vue_Apollo_Blog.md'
  - 'Server-side rendered app with Next.js and Apollo': 'examples/Server-side_rendered_app_with_nextjs_and_apollo.md'
  - 'Star Wars App with Expo': 'examples/Star_Wars_Expo.md'
- Guides:
  - 'Adding Members to your Team': 'guides/Adding_members_to_team.md'
  - 'Using Permanent Auth Tokens': 'guides/Using_permanent_auth_tokens.md'
  - 'Publishing Workflows': 'guides/Publishing_workflow.md'
  - 'Using Aliases for your API': 'guides/Using_aliases_for_api.md'
  - 'Export Schema and Content': 'guides/Export_schema_and_content.md'
  - 'Import simple data': 'guides/Import_simple_data.md'
  - 'Using Nested Mutations': 'guides/Using_Nested_Mutations.md'
  - 'Changing Your Email and Password': 'guides/User_Settings.md'
  - 'Using Translations': 'guides/Using_translations.md'
  - 'Uploading Images to GraphCMS': 'guides/Uploading_images.md'
  - 'Import Contentful Projects': 'guides/Import_contentful_projects.md'
- API:
  - 'Simple': 'api/API_simple.md'
  - 'Relay': 'api/API_relay.md'
- hidden: 
  - 'New GraphCMS Beta': 'New_GraphCMS_Beta.md'
#- New API:
#  - 'Concepts': 'prisma-api/Concepts.md'
#  - 'Queries': 'prisma-api/Queries.md'
#  - 'Mutations': 'prisma-api/Mutations.md'